In [15]:
import tensorflow as tf

In [16]:
tf.constant(b"hello world") # byte string useful for NLP

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [19]:
a = tf.constant(10)
b = tf.constant(20)

c = a+b

print(c)

tf.Tensor(30, shape=(), dtype=int32)


In [20]:
u = tf.constant([ord(i) for i in "hello world"])

In [21]:
u

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([104, 101, 108, 108, 111,  32, 119, 111, 114, 108, 100], dtype=int32)>

In [24]:
d = tf.strings.unicode_encode(u, "UTF-8")

In [25]:
d

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [26]:
tf.strings.length(d, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=11>

# Ragged Tensor

In [27]:
# Special type of tensor that represents a list of array of differnt sizes, It is a tensor with one or more ragged dimensions.

# First dimension is regular (uniform)
# Second dimension is ragged

In [29]:
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [], [6]])

In [30]:
print("Ragged Tensor:")
print(ragged_tensor)

Ragged Tensor:
<tf.RaggedTensor [[1, 2, 3], [4, 5], [], [6]]>


In [31]:
ragged_tensor.shape

TensorShape([4, None])

In [32]:
ragged_tensor[1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>

In [33]:
ragged_tensor[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [34]:
r2 = tf.ragged.constant([[8,9], [], [10,20]])

In [35]:
tf.concat([ragged_tensor, r2], axis=0)

<tf.RaggedTensor [[1, 2, 3], [4, 5], [], [6], [8, 9], [], [10, 20]]>

# Sparse tensors

In [40]:
s = tf.SparseTensor(indices=[[0, 0], [1, 0]],
                    values=[1, 2],
                    dense_shape=[3, 4])

In [41]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [42]:
s*42

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 0]], shape=(2, 2), dtype=int64), values=tf.Tensor([42 84], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

# Sets

In [46]:
a = tf.constant([[1,2,3]])
b = tf.constant([[5,6,7,8]])

u = tf.sets.union(a, b)

In [47]:
u

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [0 6]], shape=(7, 2), dtype=int64), values=tf.Tensor([1 2 3 5 6 7 8], shape=(7,), dtype=int32), dense_shape=tf.Tensor([1 7], shape=(2,), dtype=int64))

In [48]:
tf.sparse.to_dense(u)

<tf.Tensor: shape=(1, 7), dtype=int32, numpy=array([[1, 2, 3, 5, 6, 7, 8]], dtype=int32)>

In [49]:
intersection = tf.sparse.to_dense(tf.sets.intersection(a, b))

In [50]:
print(intersection)

tf.Tensor([], shape=(1, 0), dtype=int32)


# Queue ( Dont use them its 2025 )

In [52]:
# RandomShuffleQueue: Allows elements to be dequeued in a random order, adding randomness to the data processing pipeline.

# PriorityQueue: Dequeues elements based on their assigned priorities, useful for prioritized task scheduling.